version: "3"

services:
  react-app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /app/node_modules
      - .:/app

  tests:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.dev
    restart: always
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
